# lec07. numpy

* 리스트(list) vs 배열(array)
* [1,2,3]           [1 2 3]

- 패키지 설치
!pip install numpy

In [2]:
import numpy as np

In [3]:
arr = np.array( [1,2,3])
print(arr)

[1 2 3]


* 직접 만들기 불가

* arr = np.array([iterable])

## Array 생성

In [4]:
arr = [1, 2, 3]
print(arr)

[1, 2, 3]


In [5]:
# 1차 array
arr = np.array( [1,2,3])
print(arr)
print(type(arr))
print(arr.shape) #(3,)  : 1차

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [6]:
# 2차 array
list = [[1, 2, 3],
        [4, 5, 6]
       ]
arr2 = np.array(list)
print(arr2)
print(type(arr2))
print(arr2.shape) # 2행3열 - 2차 디멘전

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [7]:
# 3차 array
list = [
        [[1, 2, 3],
        [4, 5, 6]
        ]
        ,
        [[11, 12, 13],
        [14,15,16]
        ]
        ]
arr3 = np.array(list)
print(arr3)
print(type(arr3))
print(arr3.shape) # (2,2,3)  : 3차 디멘전

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
<class 'numpy.ndarray'>
(2, 2, 3)


## array 연산
- 개별 데이터에 대한 연산

In [8]:
list = [1,2,3]
arr = np.array(list)
print(list, arr)
print(list[1], arr[1])
print(len(list), len(arr))

[1, 2, 3] [1 2 3]
2 2
3 3


In [9]:
list * 3 # 리스트는 박스채로 건든다.

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [10]:
arr*3 # array는 요소들 값에 곱해준다.

array([3, 6, 9])

In [11]:
sal = [1000, 2000, 3000]
comm = [100, 200, 300]
sal2 = np.array(sal)
comm2 = np.array(comm)
sal2+comm2

array([1100, 2200, 3300])

In [12]:
temp = []
for i, v in enumerate(sal):
    temp.append(v+comm[i])
temp

[1100, 2200, 3300]

- numpy : numerical python

- 선형대수 행렬 내적

In [13]:
a = [[1,2],
     [3,4]]
b = [1,2]
a2 = np.array(a)
b2 = np.array(b)
print(a2*b2)
print(a2.dot(b2)) # (2,2) (2,1) = (2,)

[[1 4]
 [3 8]]
[ 5 11]


In [14]:
list = ['a', 1, 'c'] 
arr = np.array(list)
print(arr)

['a' '1' 'c']


In [15]:
list = [1,2,'c']
arr = np.array(list)
print(arr)

['1' '2' 'c']


In [16]:
type(arr[1])

numpy.str_

## 수학

In [17]:
# + : np.add()
# - : np.substract()
# * : np.multiply()
# / : np.divide()
# dot : 내적
# **2 : 제곱 np.square()
# root : 제곱근 np.sqrt()
# e : 지수 exp()
# log : 로그 log()
# 반올림 round() 올림 ceil() 버림 floor()

In [18]:
arr = np.array([4,9, 16])
print(arr*2)
print(arr**2)
print(np.square(arr))
print(np.sqrt(arr))

[ 8 18 32]
[ 16  81 256]
[ 16  81 256]
[2. 3. 4.]


In [19]:
a = np.array([[1,2] ,[3,4], [5,6]])
print(a)
print(a.shape) #----------------()가 없다 주의!!!
print(a.ndim) # 차수 알려준다. 괄호 2개 겹쳐있으니까 2차
print(type(a))
print(a.dtype)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2
<class 'numpy.ndarray'>
int32


In [20]:
b= np.array([[6],[2],[3]])
b.shape
print(b)

[[6]
 [2]
 [3]]


## 그룹 연산
* sum() max() min() mean() len()

In [21]:
list2 = [1,2,3,4,5]
sum(list2)

15

In [22]:
list = [1,2,3,4,5]
sum = 0
for n in list:
    sum+=n
print(sum)

15


In [23]:
max(list)

5

In [31]:
list_3 = [1,2,3,4,5]
arr = np.array(list_3)
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(len(arr))
print(arr.std()) # 편차


15
3.0
5
1
5
1.4142135623730951


## arange()
- list: range(5) :[0,1,2,3,4]
- array: np.arange(5)

In [42]:
list2 = [i for i in range(5)]
print(list2)
list2[1:4]

[0, 1, 2, 3, 4]


[1, 2, 3]

In [33]:
a= [1,2,3]
a

[1, 2, 3]

In [34]:
import numpy as np

- [줄, 칸] ==[s:e, s:e]

In [56]:
arr = np.array([[1,2], [3,4], [5,6]])
print(arr[0:2, 1:]) # --- : 기호 사용해야 세로로 출력
print(arr[0:2, 1:2]) # ---가로로 출력 : 주의

[[2]
 [4]]
[[2]
 [4]]


In [71]:
list4 = [i for i in range(5)]
# del list  - np에 자체적으로 list라는게 있어서 함수 list랑 겹침.
list4 = list(range(5))
print(list4[1:4])

[1, 2, 3]


In [72]:
data_list = [
              [7654,'MARTIN',1250, 400, 10],
              [7934,'MILLER',1300, 500, 20],
              [7876,'ADAMS' ,1100,   0, 30] 
           ]
data = np.array(data_list)
print(data.shape)
print(data.ndim)
print(data)

(3, 5)
2
[['7654' 'MARTIN' '1250' '400' '10']
 ['7934' 'MILLER' '1300' '500' '20']
 ['7876' 'ADAMS' '1100' '0' '30']]


In [73]:
data[1:, 1:4]

array([['MILLER', '1300', '500'],
       ['ADAMS', '1100', '0']], dtype='<U11')

In [74]:
data[:,:2]

array([['7654', 'MARTIN'],
       ['7934', 'MILLER'],
       ['7876', 'ADAMS']], dtype='<U11')

In [75]:
data[:, 4:]

array([['10'],
       ['20'],
       ['30']], dtype='<U11')

In [76]:
data[2:]

array([['7876', 'ADAMS', '1100', '0', '30']], dtype='<U11')

In [77]:
word = 'hello'
print(word[2:4])

ll


In [78]:
emp = [1,2,3,4,5]
emp[2:4]

[3, 4]

## 난수: np.random.랜덤함수()
* randint(n, size=(3,4) ) : 0 ~ n-1범위 내에서 균일분포의 정수난수를 발생
* rand()   : 난수 발생 균등분포를 따르는 난수 발생 (음수값X)
* randn() : 표준 정규분포를 따르는 난수 발생 (음수값O)


In [100]:
import numpy as np
a = np.random.randint(10) # 0~9까지의 숫자 반환
print(a)

8


In [105]:
temp = np.random.randint(46, size=6) # 6개 반환

In [106]:
np.sort(np.random.randint(46, size = 6))

array([18, 18, 24, 28, 38, 43])

In [107]:
set(temp[:6])

{3, 7, 14, 23, 38}

In [108]:
np.random.randint(46, size=(2,3))

array([[37,  4, 17],
       [34,  6, 14]])

In [117]:
np.random.seed(42) # 여러번 뽑아도 처음 뽑은게 그대로 나올 수 있도록
np.random.randint(10)

6

## CRUD

### 조회 R
- 인덱스
- 슬라이싱
- 조건 : isin() any() all()

In [118]:
'3' in ['3', '6', '9']

True

In [120]:
np.isin('3', ['3', '6', '9'])

array(True)

In [123]:
arr = np.array([1,2,3,4,5])
np.where(arr>3) # 3보다 큰게 있어? -> 인덱스 반환

(array([3, 4], dtype=int64),)

In [127]:
arr[np.where(arr>3)] # 결과값 뽑아내주기

array([4, 5])

In [135]:
arr = np.array([1,2,3,4,5])
np.any(arr<5)

True

In [130]:
arr = np.array([1,2,3,4,5])
np.all(arr<5)

False

In [142]:
# list에서 함수
emp = [1,2,3]
print(emp)
emp.append(4)
print(emp)
emp.insert(1,99)
print(emp)
emp.remove(4)
print(emp)

[1, 2, 3]
[1, 2, 3, 4]
[1, 99, 2, 3, 4]
[1, 99, 2, 3]


In [143]:
arr = np.array([1,2,3])
print(arr) #[1,2,3]

arr = np.append(arr, (4,5)) 
print(arr)

arr = np.append(arr, [4,5]) 
print(arr)

arr = np.insert(arr, 1, 99)
print(arr)

arr = np.delete(arr, [4,5])
print(arr)

[1 2 3]
[1 2 3 4 5]
[1 2 3 4 5 4 5]
[ 1 99  2  3  4  5  4  5]
[ 1 99  2  3  4  5]


## 좌우 붙이기
- 그냥 hstack 쓰자
- np.r
- np.hstack
- np.concatenate((a,b), axis=0)

In [150]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.r_[a,b])
print(np.hstack([a,b]))
print(np.concatenate((a,b), axis=0))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


## 위아래 붙이기
- 그냥 vstack 쓰자

In [165]:
print(np.r_[[a], [b]])
print(np.vstack((a, b)))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


## 세로줄로 붙이기


In [166]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.column_stack([a,b]))

[[1 4]
 [2 5]
 [3 6]]


## reshape(행, 열)

In [174]:
np.random.seed(42)
arr = np.random.randint(30, size=(4,3))
print(arr)
print(arr.shape)

[[ 6 19 28]
 [14 10  7]
 [28 20  6]
 [25 18 22]]
(4, 3)


4, 3 -- 6, 2    --3, 4       --5, 남으면 에러

In [175]:
temp = arr.reshape(6,2)
print(temp)
print(temp.shape)

[[ 6 19]
 [28 14]
 [10  7]
 [28 20]
 [ 6 25]
 [18 22]]
(6, 2)


In [176]:
temp = arr.reshape(-1,4) # -1은 너가 계산해
print(temp)
print(temp.shape)

[[ 6 19 28 14]
 [10  7 28 20]
 [ 6 25 18 22]]
(3, 4)


# arr.reshape(줄, 칸)
- reshape(-1, )의 의미: 컴퓨터가 알아서 계산해라
- reshape(-1) 의 의미 : 1차

In [182]:
print(temp)
print(temp.reshape(-1))
print(temp.reshape(-1,3))

[[ 6 19 28 14]
 [10  7 28 20]
 [ 6 25 18 22]]
[ 6 19 28 14 10  7 28 20  6 25 18 22]
[[ 6 19 28]
 [14 10  7]
 [28 20  6]
 [25 18 22]]


## axis
- axis=0 : row
- axis=1 : col

In [185]:
arr = np.array([[1,2,3], [10, 20, 30]])
print(arr)
print(arr.sum())
print(np.sum(arr))
print(arr.sum(axis=1))
print(arr.sum(axis=0))

[[ 1  2  3]
 [10 20 30]]
66
66
[ 6 60]
[11 22 33]


## 기타 : 예약어는 변수명으로 사용하지마셔요

In [81]:
import numpy as np
list = [1,2,3]
del list # 메모리에서 list 지우기
list(map(int, ['1', '2', '3']))

[1, 2, 3]

In [83]:
# del list
__builtins__.list(map(int, ['10', '20', '30'])) # del 쓰거나 builins 쓰고 함수 쓰거나


[10, 20, 30]